### ISSUE TITLE
dicom_io

### ISSUE THREAD

**Issue by keegan-mcn** [jasqs/FREDtools#1]
Accessing
StructureSetROISequence.ROIGenerationAlgorithm
in _getStructureContoursByName is not gauranteed.

if not ROINumber:
should be replaced with
if ROINumber is None:
for the case where ROINumber = 0

**Comment by jasqs** [comment]
I have solved both issues with ROIGenerationAlgorithm and ROINumber. 
The changes are committed and new fredtools v. 0.6.45 available from pip. 

Confirm if the problem is solved.
